name: PreventDamageOnLogin
main: net.thedarktide.celeo.preventdamageonlogin.PreventDamage
author: Celeo
version: 1.8
commands:
  preventdamage:
    description: Commands
    usage: /<command> <parameters>