name: Prevent Damage on Login
main: net.thedarktide.celeo.preventdamageonlogin.PreventDamage
author: Celeo
version: 1.0
commands:
  PreventDamage:
    description: Sets this plugin to on|off
    usage: /<command>
  SetDelay:
    description: Sets the amount of time for no damage after login
    usage: /<command> <time>