name: PreventDamage
author: Celeo
version: 1.6.1
main: net.thedarktide.celeo.preventdamage.PreventDamage
description: Prevents players from taking advantage of the login invulnerabilty by preventing them from doing damage during that time.