name: PreventDamage
main: net.thedarktide.celeo.preventdamage.PreventDamage
author: Celeo
version: 1.3
description: Prevents players from taking advantage of the login invulnerabilty by preventing them from doing damage during that time.